define(`PITCH', 8000)
define(`PAD_LENGTH', 31)
define(`PAD_WIDTH', 15)
define(`ISTART', 1)
define(`XPADS', 8)
define(`YPADS', 8)
define(`X_LENGTH', 354)
define(`Y_LENGTH', 354)
PKG_GEN_QFP(QFP32, , )
